SET SERVEROUTPUT ON;

BEGIN
EXECUTE IMMEDIATE 'DROP ROLE CUSTOMER_ROLE';
EXCEPTION
WHEN OTHERS THEN
    IF SQLCODE = -1924 THEN
     DBMS_OUTPUT.PUT_LINE('CREATING ROLE CUSTOMER_ROLE');
    END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP ROLE SUPPLIER_ROLE';
EXCEPTION
WHEN OTHERS THEN
    IF SQLCODE = -1924 THEN
     DBMS_OUTPUT.PUT_LINE('CREATING ROLE SUPPLIER_ROLE');
    END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP ROLE LOGISTICS_ROLE';
EXCEPTION
WHEN OTHERS THEN
    IF SQLCODE = -1924 THEN
     DBMS_OUTPUT.PUT_LINE('CREATING ROLE LOGISCTIC_ROLE');
    END IF;
END;
/

CREATE ROLE CUSTOMER_ROLE;
GRANT SELECT, INSERT ON ORDERS TO CUSTOMER_ROLE;
GRANT SELECT, INSERT, UPDATE ON PRODUCTORDER TO CUSTOMER_ROLE;
GRANT SELECT, INSERT, UPDATE ON CUSTOMERS TO CUSTOMER_ROLE;

CREATE ROLE SUPPLIER_ROLE;
GRANT SELECT, INSERT, UPDATE ON PRODUCTS TO SUPPLIER_ROLE;
GRANT SELECT, INSERT,  UPDATE ON SUPPLIERS TO SUPPLIER_ROLE;
GRANT SELECT, UPDATE ON PRODUCTSUPPLY TO SUPPLIER_ROLE;

CREATE ROLE LOGISTICS_ROLE;
GRANT SELECT ON PRODUCTS TO LOGISTICS_ROLE;
GRANT SELECT ON CATEGORIES TO LOGISTICS_ROLE;
GRANT SELECT ON SUPPLIERS TO LOGISTICS_ROLE;
GRANT SELECT, UPDATE ON ORDERS TO LOGISTICS_ROLE;
GRANT SELECT ON CUSTOMERS TO LOGISTICS_ROLE;


DECLARE
V_USER VARCHAR(100);
V_DROP_SQL VARCHAR(500);
BEGIN
FOR I IN (
WITH DESIRED_USERS AS (
SELECT 'CUSTOMER' USERNAME FROM DUAL
UNION ALL
SELECT 'SUPPLIER' FROM DUAL
UNION ALL
SELECT 'LOGISTIC_ADMIN' FROM DUAL
)
SELECT DU.USERNAME FROM DESIRED_USERS DU JOIN ALL_USERS AU ON DU.USERNAME = AU.USERNAME
)
LOOP
EXECUTE IMMEDIATE 'DROP USER ' || I.USERNAME || ' CASCADE';
END LOOP;
EXCEPTION
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG. CONTACT ADMIN');
END;
/

CREATE USER CUSTOMER IDENTIFIED BY "TeamRelationalNinjas2023#";
GRANT CUSTOMER_ROLE TO CUSTOMER;
GRANT CONNECT,RESOURCE TO CUSTOMER;

CREATE USER SUPPLIER IDENTIFIED BY "TeamRelationalNinjas2023#";
GRANT SUPPLIER_ROLE TO SUPPLIER;
GRANT CONNECT,RESOURCE TO SUPPLIER;

CREATE USER LOGISTIC_ADMIN IDENTIFIED BY "TeamRelationalNinjas2023#";
GRANT LOGISTICS_ROLE TO LOGISTIC_ADMIN;
GRANT CONNECT,RESOURCE TO LOGISTIC_ADMIN;





