-- Run this script as LOGISTIC_ADMIN
ALTER SESSION SET CURRENT_SCHEMA = IMS_ADMIN;
SET SERVEROUTPUT ON;


EXECUTE TOGGLE_SHIP_STATUS_UP(4000);
EXECUTE TOGGLE_SHIP_STATUS_UP(4000);
EXECUTE TOGGLE_SHIP_STATUS_UP(4000);
EXECUTE TOGGLE_SHIP_STATUS_UP(4000);
EXECUTE TOGGLE_SHIP_STATUS_UP(4000);

EXECUTE TOGGLE_SHIP_STATUS_UP(4005);
EXECUTE TOGGLE_SHIP_STATUS_UP(4005);
EXECUTE TOGGLE_SHIP_STATUS_UP(4006);
EXECUTE TOGGLE_SHIP_STATUS_UP(4006);
EXECUTE TOGGLE_SHIP_STATUS_UP(4007);
EXECUTE TOGGLE_SHIP_STATUS_UP(4007);
EXECUTE TOGGLE_SHIP_STATUS_UP(4008);
EXECUTE TOGGLE_SHIP_STATUS_UP(4008);
EXECUTE TOGGLE_SHIP_STATUS_UP(4009);
EXECUTE TOGGLE_SHIP_STATUS_UP(4009);



SELECT * FROM logistic_admin_order_status;